### ISSUE TITLE
netdisco-rancid-export

### ISSUE THREAD

**Issue by LBegnaud** [netdisco/netdisco-docker#13]
finally getting around to testing this new-and-improved version of netdisco-docker. Seems by far better than what I had fumbled and put together. 

do you know if it's possible to automate the rancid export script with what we currently have? I don't think cron is included.

I've gotten around it in the short term by making a cron job on the host os:

`docker exec -it netdisco_netdisco-backend_1 netdisco-rancid-export`

but obviously this isn't ideal.

**Comment by ollyg** [comment]
Hi @LBegnaud there is a new way to do this which you can use. The RANCID builder has been ported to be a core backend worker:

https://metacpan.org/pod/App::Netdisco::Worker::Plugin::MakeRancidConf

Note that the settings/config is slightly different to the old cron routine, and you'll need to add to `schedule` to enable it. You can use the `rancid_home` setting to write out to the mounted filesystem that's shared from the docker host system.

Hope this helps,
