### ISSUE TITLE
Docker error regarding 'version' in docker-compose.yml

### ISSUE THREAD

**Issue by BioSehnsucht** [netdisco/netdisco-docker#14]
OS: CentOS Linux release 7.5.1804 (Core)
Docker version: docker.x86_64                                                            2:1.13.1-63.git94f4240.el7.centos                                                            @extras
When attempting to follow the instructions to start the container : 

```
# docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

From some googling, I tried changing the following:
```
version: '2.3'
```
to
```
version: '2'
```

And this appears to have worked.

**Comment by inphobia** [comment]
after looking at the docker docs it's not quite clear what the actual syntax should be for `version`, single or double quotes.

**Comment by LBegnaud** [comment]
I believe this is a function of the docker-compose version. @BioSehnsucht mind sharing that version?

![image](https://user-images.githubusercontent.com/15981748/64039322-f8329500-cb1f-11e9-8171-fce49e46faf8.png)


for instance these are my versions and the version string in `docker-compose.yml` works fine
