### ISSUE TITLE
circleci config

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco-docker#15]
so i noticed the docker images no longer have builds on the docker hub after 2.038028

after look around i did see 1 strange thing. the circleci config has unicode quotes for some reason.

these commands:
```
--build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
```

it might not be very clear but the date format is using non ascii double quotes, which produce:
```
date -u +”%Y-%m-%dT%H:%M:%SZ”
”2019-02-28T17:24:34Z”
```

instead of
```
date -u +"%Y-%m-%dT%H:%M:%SZ"
2019-02-28T17:25:20Z
```

first ref:
https://github.com/netdisco/netdisco-docker/blob/dc4e52dec6ca32845d3c0de88eae0cb52c1d47a9/.circleci/config.yml#L50

last ref:
https://github.com/netdisco/netdisco-docker/blob/dc4e52dec6ca32845d3c0de88eae0cb52c1d47a9/.circleci/config.yml#L152

and a bunch more in between.

**Comment by ollyg** [comment]
Can you give the link where you're not seeing the Netdisco builds?

If I click the "docker images ready" icon in the Netdisco wiki or homepage, then click tags, it shows the 2.040... images are there.

**Comment by inphobia** [comment]
if you click builds there instead of tags you'll see the actual builds seem to have stopped.

**Comment by ollyg** [comment]
I think that's docker hub being stupid. It's an awful system. The builds happen over in circle CI and work fine - the tags would not be appearing if the builds were not working, I believe.
