### ISSUE TITLE
Instructions not fully working

### ISSUE THREAD

**Issue by luismanson** [netdisco/netdisco-docker#17]
Hello, I've been unable to run the compose file. 

> netdisco-postgresql_1 seems to start fine, and own most of the log output, the problem seem to be on 
> 
> netdisco-backend_1     | Attempting to create directory /home/netdisco/perl5
> netdisco-web_1         | Attempting to create directory /home/netdisco/perl5
> 
> netdisco-backend_1     | error: cannot find Netdisco config at /home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/environments/deployment.yml or /home/netdisco/environments/deployment.yml
> 
> netdisco-web_1         | error: cannot find Netdisco config at /home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/environments/deployment.yml or /home/netdisco/environments/deployment.yml
> 

Also, the mkdir shown has a relative path, is this supposed to be run in /home? and from which user do I need to call docker-compose? 

thanks.

**Comment by inphobia** [comment]
while i'm a docker noob, why do all your containers have a _1 suffix? are there multiple versions running or did some old config remain?

**Comment by luismanson** [comment]
I did run compose more than once, while trying to understand the problem.

**Comment by inphobia** [comment]
as i don't know enough about docker and i deleted my testsetup a few days ago i would suggest to try & clean out your config (volumes, containers & such) and give it another go.

the best i can do to get a new docker setup for testing will not be in the next few weeks...

**Comment by luismanson** [comment]
Ok, thanks. I've removed al files from home/netdisco, then executed the commands inside the netdisco home. 
It started all containers and loaded the admin. Thanks :)

**Comment by inphobia** [comment]
coolness, we'll need to look into this at some later time but docker support ain't my main prio atm, perhaps you or others want to give it a go?

**Comment by luismanson** [comment]
I'll look into it, I've too understand how docker works

**Comment by KDGundermann** [comment]
Instructions still not updated :-(
- `mkdir -p netdisco/{logs,config,nd-site-local}`
  creates dirs relative to the current directory. But my current directory is /home/klaus ?!?

**Comment by ollyg** [comment]
Hi @KDGundermann the instructions earlier say `su - netdisco` which would put you in the Netdisco user home.

**Comment by KDGundermann** [comment]
@ollyg: sorry but I can't see this line in README.md

**Comment by inphobia** [comment]
> Hi @KDGundermann the instructions earlier say `su - netdisco` which would put you in the Netdisco user home.

can't say i can find that line in the readme file or any other file after searching the netdisco-docker repo.

no docker user but perhaps changing:
```
mkdir -p netdisco/{logs,config,nd-site-local}
sudo chown -R netdisco:netdisco netdisco
```

to
```
mkdir -p ~netdisco/{logs,config,nd-site-local}
sudo chown -R netdisco:netdisco ~netdisco
```

`~` followed by a username is a reference to that user's homedir. dunno if it works in all shells, but i think it's posix mandated.

**Comment by ollyg** [comment]
apologies @KDGundermann I was looking a different file! we can update the README

**Comment by we-sell-bags** [comment]
it is still WRONG.....
here:
https://hub.docker.com/r/netdisco/netdisco


Only if you are on Linux:

sudo groupadd netdisco -g 901
sudo useradd -u 901 -p x -g netdisco netdisco
mkdir -p netdisco/{logs,config,nd-site-local}
sudo chown -R netdisco:netdisco netdisco

And then (for everyone):

curl -Ls -o docker-compose.yml https://tinyurl.com/nd2-dockercompose
docker-compose up

**Comment by ollyg** [comment]
Did you know you can easily do a pull request inside the GitHub web interface to offer a patch to fix this? Click the edit icon on the file. Good for instructions if needed. 

It would help us greatly, we are all volunteers.

**Comment by we-sell-bags** [comment]
Did you know you can search the whole repository for  duplicate items in all instruction sources, instead of just fixing one location.

or free up your obviously very valuable time, by  implementing Tim Berners-Lee's gift to humanity...
and having ONE definitive copy....

**Comment by ollyg** [comment]
Hi @luismanson and @KDGundermann I believe I edited the README.md file correctly:
https://github.com/netdisco/netdisco-docker/blob/master/README.md

Please would you confirm this is what you wanted (I am not sure if there is another location to update)?

**Comment by luismanson** [comment]
> Please would you confirm this is what you wanted (I am not sure if there is another location to update)?

Yes, thanks!!! Just check the line 25, as i think it has to be split in two lines.

**Comment by inphobia** [comment]
seems fine to me as well
