### ISSUE TITLE
"latest" not found

### ISSUE THREAD

**Issue by StewAlexanderACC** [netdisco/netdisco-docker#18]
Output on my Ubuntu docker host:
```
support@netdisco-new:~$ sudo docker pull netdisco/netdisco
Using default tag: latest
Error response from daemon: manifest for netdisco/netdisco:latest not found
```

**Comment by inphobia** [comment]
netdisco's containers are split up atm, so docker pull will not work. can you try docker-compose instead?

```
curl -Ls -o docker-compose.yml https://tinyurl.com/nd2-dockercompose
docker-compose up
```

**Comment by StewAlexanderACC** [comment]
Old issue, already resolved by using 
```
sudo docker pull netdisco/netdisco:latest-do 
```

Worked for me

Further instructions:
[NetDisco-New - Support.pdf](https://github.com/netdisco/netdisco-docker/files/3401988/NetDisco-New.-.Support.pdf)

**Comment by LBegnaud** [comment]
seems this is resolved. Please reopen if you have more information to add.

**Comment by inphobia** [comment]
perhaps it's confusing that https://hub.docker.com/r/netdisco/netdisco says:

![image](https://user-images.githubusercontent.com/39005454/64042840-15d51e00-cb63-11e9-977c-1cb63adda0a4.png)

but no idea how to change that.
