### ISSUE TITLE
can i get a network topology graph with netdiso

### ISSUE THREAD

**Issue by reckless-huang** [netdisco/netdisco-docker#30]
Dear friends
   i want print a network topology graph to help my work ,and i get it 
![图片](https://user-images.githubusercontent.com/53162954/80776518-2841a480-8b95-11ea-9cdd-824c419d7753.png)
It's not clear to me ,what do i need to do .

**Comment by ollyg** [comment]
Hi @reckless-huang 
You should install netdisco using the docker images or on a server using the instructions here: https://metacpan.org/pod/App::Netdisco
Then you can discover some devices on your network (instructions are in the link above)
Then in the web interface you can browse to one of the devices and view the Neighbors tab to see the map. User guide for the map is here in the wiki: https://github.com/netdisco/netdisco/wiki/Network-Map
