### ISSUE TITLE
ssh pulling doesn't works cause  no matching method

### ISSUE THREAD

**Issue by Dees7** [netdisco/netdisco-docker#32]
Hello.
We have a lot of Cisco ASA  (5506-X\ASA5505)
Software Version from 7.2(4)  till 9.8(4)12 
It can't be polled arp.  asa supports only

    dh-group1-sha1   Diffie-Hellman group 2
    dh-group14-sha1  Diffie-Hellman group 14

So, if I check in console

    $netdisco-do  macsuck -d 10.10.209.2 -D 99
    [99] 2020-07-31 17:46:57  info App::Netdisco version 2.046001 loaded.
    [99] 2020-07-31 17:46:58  info macsuck: [10.10.209.2] started at Fri Jul 31 17:46:58 2020
    [99] 2020-07-31 17:46:58 debug macsuck: running with timeout 600s
    [99] 2020-07-31 17:46:58 debug => running workers for phase: check
    [99] 2020-07-31 17:46:58 debug -> run worker check/_base_/0
    [99] 2020-07-31 17:46:58 debug is_macsuckable: 10.10.209.2 has no layer 2 capability
    [99] 2020-07-31 17:46:58 debug macsuck skipped: 10.10.209.2 is not macsuckable
    [99] 2020-07-31 17:46:58  info macsuck: finished at Fri Jul 31 17:46:58 2020
    [99] 2020-07-31 17:46:58  info macsuck: status info: macsuck skipped: 10.10.209.2 is not macsuckable
    
    $ssh -l user 10.10.209.2 
    Unable to negotiate with 10.10.209.2 port 22: no matching key exchange method found. Their offer: diffie-hellman-group1-sha1
    (and if changed):
    $ssh -l user 10.10.209.2 
    Unable to negotiate with 10.10.209.2 port 22: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1
    $cat /etc/os-release 
    PRETTY_NAME="Alpine Linux v3.12"

## Your Environment

Software | Version
-- | --
App::Netdisco 	| 2.46.1
SNMP::Info 	|3.70
DB Schema 	|63
PostgreSQL 	|12.00.2
Perl 	|5.30.3
docker engine version:  | 19.03.8
docker-compose version: | 1.25.5
host operating system  | CentOS Linux 8
netdisco/netdisco | latest-backend    
netdisco/netdisco | latest-web        
netdisco/netdisco | latest-postgresql 

## Config info (deployment.yml and docker env settings)

    - tag: 'ASA arp check'
      driver: cli
      platform: ASA
      username: user
      password: pass
      enable_password: pass
      only:
         - '10.10.209.2'

**Comment by inphobia** [comment]
see https://github.com/netdisco/netdisco/wiki/Configuration#device_auth

ssh_master_opts option.

**Comment by rc9000** [comment]
Hi @Dees7 

Looks like you need to enable DSS key exchange algorithms. You can either put this into the ssh_master_opts as @inphobia says, or in the ssh_config file

https://www.openssh.com/legacy.html

    Host somehost.example.org
	    KexAlgorithms +diffie-hellman-group1-sha1

    ssh -oHostKeyAlgorithms=+ssh-dss user@legacyhost

As a side note only the arpnip action uses SSH, macsuck like in your example is SNMP-only

**Comment by Dees7** [comment]
Thank all.
Docker doesn't used ~/.ssh/ssh_config  
I edit /etc/ssh/ssh_config  (mapped from host to keep after update). and  now all ok. works
