### ISSUE TITLE
Latest cisco MIB has been in netdisco-mibs for a year but are missing in the latest containerized builds

### ISSUE THREAD

**Issue by letienne** [netdisco/netdisco-docker#33]
## Expected Behavior

Latest docker image should include latest MIBs.

The latest Cisco MIB has been in netdisco-mibs for more than a year:
https://github.com/netdisco/netdisco-mibs/blob/master/cisco/CISCO-PRODUCTS-MIB.my
(last modified september 2019).

However the bundled file in the latest docker-backend image is dated from 2018 and stops at "ciscoProducts 2705" :
318.9K Dec 30  2018 CISCO-PRODUCTS-MIB.my

## Current Behavior

Older version of the file is bundled.

## Steps to Reproduce (for bugs)

1.  Docker pull/run -latest (2.46.5 at the time of this writing)
2.  docker exec -t <containerid> sh -c "ls -alh /home/netdisco/netdisco-mibs/cisco/CISCO-PRODUCTS*"
-rw-rw-r--    1 netdisco netdisco  318.9K **Dec 30  2018** /home/netdisco/netdisco-mibs/cisco/CISCO-PRODUCTS-MIB.my
3. Note that the file is not the latest 

## Context

Wrong products displayed with latest Cisco devices.

## Your Environment

* netdisco container versions: 2.46.5
  * netdisco-postgresql: 2.46.5
  * netdisco-backend: 2.46.5
  * netdisco-web: 2.46.5
* docker engine version:  irrelevant
* docker-compose version:  irrelevant
* host operating system: rhel

## Config info (deployment.yml and docker env settings)

irrelevant

**Comment by inphobia** [comment]
i thought i saw this issue before. netdisco-mibs get tagged x.xxx.

for some reason however we once released 4.13 instead of 4.013 and the logic used thinks 4.13 is greater than the recently release 4.019
https://github.com/netdisco/netdisco-docker/blob/75ed4476deb8004d1da30709be2123c41f88c17d/netdisco-backend/Dockerfile#L17-L20

i've alrdy renamed netdisco-mibs 4.13 to 4.013, but it seems the git tag might be still around....

**Comment by inphobia** [comment]
oh, it seems github has a handy feature to remove tags now, so removed the incorrect 4.13 tag, can you try again?

before deleting the tag i got this:
```
curl -sL https://api.github.com/repos/netdisco/netdisco-mibs/tags | jq '.[]|.tarball_url|select(test("tarball/\\d+\\.\\d+$"))' | sort -rg | head -n1
"https://api.github.com/repos/netdisco/netdisco-mibs/tarball/4.13"
```

after deleting the tag i get the latest version:
```
curl -sL https://api.github.com/repos/netdisco/netdisco-mibs/tags | jq '.[]|.tarball_url|select(test("tarball/\\d+\\.\\d+$"))' | sort -rg | head -n1
"https://api.github.com/repos/netdisco/netdisco-mibs/tarball/4.019"
```

i'm no git expert, perhaps the tag was readded by accident when someone merged their tree. we'll need to keep an eye on this.

**Comment by inphobia** [comment]
pull request #35 hopefully solves this issue forever.

**Comment by letienne** [comment]
Thanks, I'll try with the next container build

**Comment by letienne** [comment]
I can confirm that my cisco.Product.XXXX have now become 9500FixedSwitchStack in the inventory, confirming that the MIBs have been upgraded !

Thanks for the fix !
