### ISSUE TITLE
Is the docker version the same as latest released?

### ISSUE THREAD

**Issue by ntaken** [netdisco/netdisco-docker#40]
The question is in the title. It seems to me that the version with docker is App::Netdisco 2.047002.

**Comment by ntaken** [comment]
Will you update the https://hub.docker.com/r/netdisco/netdisco too?

**Comment by ollyg** [comment]
I'm sorry, we have some trouble with CircleCI automation and I'm looking into it next

**Comment by ollyg** [comment]
Hi, is fixed now (hopefully for good!), very sorry about that

https://hub.docker.com/r/netdisco/netdisco/tags?page=1&ordering=last_updated
