### ISSUE TITLE
Latest version missed in hub.docker.com again (repeated #31)

### ISSUE THREAD

**Issue by anp135** [netdisco/netdisco-docker#41]
@ollyg please fix again. docker hub has 47.002 version right now

**Comment by ollyg** [comment]
oops thanks, will look into it :(

**Comment by ollyg** [comment]
I'm sorry, we have some trouble with CircleCI automation and I'm looking into it next

**Comment by ollyg** [comment]
Hi, is fixed now (hopefully for good!), very sorry about that

https://hub.docker.com/r/netdisco/netdisco/tags?page=1&ordering=last_updated
