### ISSUE TITLE
netdisco-web_1 error can't access website.

### ISSUE THREAD

**Issue by ntaken** [netdisco/netdisco-docker#42]
## Steps to Reproduce (for bugs)
Followed Install steps.

## Context
> sudo docker-compose up

>Starting home_netdisco-postgresql_1 ... done
>Starting home_netdisco-backend_1    ... done
>Starting home_netdisco-web_1        ... done
>Attaching to home_netdisco-postgresql_1, home_netdisco-backend_1, home_netdisco-web_1
>netdisco-backend_1     | config watcher: watching /home/netdisco/environments for updates.
>netdisco-postgresql_1  | netdisco-db-entrypoint: starting pg privately to container
>netdisco-postgresql_1  | waiting for server to start....2021-10-08 09:05:27.103 CEST [9] LOG:  starting PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
>netdisco-postgresql_1  | 2021-10-08 09:05:27.103 CEST [9] LOG:  listening on IPv4 address "127.0.0.1", port 5432
>netdisco-postgresql_1  | 2021-10-08 09:05:27.104 CEST [9] LOG:  could not bind IPv6 address "::1": Address not available
>netdisco-postgresql_1  | 2021-10-08 09:05:27.104 CEST [9] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
>netdisco-postgresql_1  | 2021-10-08 09:05:27.111 CEST [9] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
>netdisco-postgresql_1  | 2021-10-08 09:05:27.124 CEST [10] LOG:  database system was shut down at 2021-10-08 09:00:38 CEST
>netdisco-postgresql_1  | 2021-10-08 09:05:27.133 CEST [9] LOG:  database system is ready to accept connections
>netdisco-postgresql_1  |  done
>netdisco-postgresql_1  | server started
>netdisco-postgresql_1  | netdisco-db-entrypoint: bringing schema up-to-date
>netdisco-web_1         | config watcher: watching /home/netdisco/environments for updates.
>netdisco-web_1         | 2021/10/08-09:05:29 Starman::Server (type Net::Server::PreFork) starting! pid(9)
>netdisco-web_1         | Resolved [*]:5000 to [::]:5000, IPv6
>netdisco-web_1         | Not including resolved host [0.0.0.0] IPv4 because it will be handled by [::] IPv6
>netdisco-web_1         | Binding to TCP port 5000 on host :: with IPv6
>netdisco-web_1         | Setting gid to "901 901"
>netdisco-web_1         | [14] 2021-10-08 07:05:29  warn App::Netdisco 2.049009 web
>netdisco-web_1         | [12] 2021-10-08 07:05:30  warn App::Netdisco 2.049009 web
>netdisco-web_1         | [10] 2021-10-08 07:05:30  warn App::Netdisco 2.049009 web
>netdisco-web_1         | [11] 2021-10-08 07:05:30  warn App::Netdisco 2.049009 web
>netdisco-web_1         | [13] 2021-10-08 07:05:30  warn App::Netdisco 2.049009 web
>netdisco-postgresql_1  | netdisco-db-entrypoint: importing OUI
>netdisco-postgresql_1  | netdisco-db-entrypoint: marking schema as up-to-date
>netdisco-postgresql_1  | netdisco-db-entrypoint: adding admin user if none exists
>netdisco-postgresql_1  | netdisco-db-entrypoint: adding session key if none exists
>netdisco-postgresql_1  | netdisco-db-entrypoint: queueing stats job
>netdisco-postgresql_1  | INSERT 0 1
>netdisco-postgresql_1  | netdisco-db-entrypoint: shutting down pg (will restart, listening for clients)
>netdisco-postgresql_1  | waiting for server to shut down....2021-10-08 09:05:30.680 CEST [9] LOG:  received fast shutdown request
>netdisco-postgresql_1  | 2021-10-08 09:05:30.689 CEST [9] LOG:  aborting any active transactions
>netdisco-postgresql_1  | 2021-10-08 09:05:30.691 CEST [9] LOG:  background worker "logical replication launcher" (PID 16) exited with exit code 1
>netdisco-postgresql_1  | 2021-10-08 09:05:30.699 CEST [11] LOG:  shutting down
>netdisco-postgresql_1  | 2021-10-08 09:05:30.949 CEST [9] LOG:  database system is shut down
>netdisco-postgresql_1  |  done
>netdisco-postgresql_1  | server stopped
>netdisco-postgresql_1  |
>netdisco-postgresql_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
>netdisco-postgresql_1  |
>netdisco-postgresql_1  | 2021-10-08 09:05:31.145 CEST [1] LOG:  starting PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
>netdisco-postgresql_1  | 2021-10-08 09:05:31.149 CEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
>netdisco-postgresql_1  | 2021-10-08 09:05:31.149 CEST [1] LOG:  listening on IPv6 address "::", port 5432
>netdisco-postgresql_1  | 2021-10-08 09:05:31.156 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
>netdisco-postgresql_1  | 2021-10-08 09:05:31.163 CEST [248] LOG:  database system was shut down at 2021-10-08 09:05:30 CEST
>netdisco-postgresql_1  | 2021-10-08 09:05:31.176 CEST [1] LOG:  database system is ready to accept connections
>netdisco-web_1         | DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
>netdisco-web_1         | DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
>netdisco-web_1         | DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
>netdisco-web_1         | DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
>netdisco-web_1         | DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
>netdisco-web_1         | Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: The setting session_cookie_key must be defined at /home/netdisco/perl5/lib/perl5/Dancer/Session/Cookie.pm line 38.
>netdisco-web_1         | Compilation failed in require at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
>netdisco-web_1         | BEGIN failed--compilation aborted at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
>netdisco-web_1         | Child process 14 exited with status 22
>netdisco-web_1         | Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: The setting session_cookie_key must be defined at /home/netdisco/perl5/lib/perl5/Dancer/Session/Cookie.pm line 38.
>netdisco-web_1         | Compilation failed in require at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
>netdisco-web_1         | BEGIN failed--compilation aborted at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
>netdisco-web_1         | Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: The setting session_cookie_key must be defined at /home/netdisco/perl5/lib/perl5/Dancer/Session/Cookie.pm line 38.
>netdisco-web_1         | Compilation failed in require at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
>netdisco-web_1         | BEGIN failed--compilation aborted at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
>netdisco-web_1         | Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: The setting session_cookie_key must be defined at /home/netdisco/perl5/lib/perl5/Dancer/Session/Cookie.pm line 38.
>netdisco-web_1         | Compilation failed in require at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
>netdisco-web_1         | BEGIN failed--compilation aborted at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
>netdisco-web_1         | Child process 10 exited with status 22
>netdisco-web_1         | Child process 11 exited with status 22
>netdisco-web_1         | Child process 12 exited with status 22
>netdisco-web_1         | Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: The setting session_cookie_key must be defined at /home/netdisco/perl5/lib/perl5/Dancer/Session/Cookie.pm line 38.
>netdisco-web_1         | Compilation failed in require at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
>netdisco-web_1         | BEGIN failed--compilation aborted at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
>netdisco-web_1         | Child process 13 exited with status 22
>netdisco-web_1         | [20] 2021-10-08 07:05:35  warn App::Netdisco 2.049009 web
>netdisco-web_1         | [23] 2021-10-08 07:05:36  warn App::Netdisco 2.049009 web
>netdisco-web_1         | [22] 2021-10-08 07:05:36  warn App::Netdisco 2.049009 web
>netdisco-web_1         | [24] 2021-10-08 07:05:36  warn App::Netdisco 2.049009 web
>netdisco-web_1         | [21] 2021-10-08 07:05:36  warn App::Netdisco 2.049009 web

From here on the netdisco-web_1 errors loop.

## Your Environment
* netdisco container versions: Latest docker-compose pull
  * netdisco-postgresql: 
  * netdisco-backend: 
  * netdisco-web: 
* docker engine version: 20.10.9
* docker-compose version: 1.27.4, build 40524192
* host operating system:  Ubuntu LTS 20.04.3

I use a local apache2 reverse proxy that have worked before:

>  <Location "/netdisco">
>    RequestHeader set X-Forwarded-Proto "https"
>    ProxyPass  http://127.0.0.1:5000/netdisco
>    ProxyPassReverse http://127.0.0.1:5000/netdisco
>   Order allow,deny
>    Allow from all

## Config info (deployment.yml and docker env settings)

>`version: '2.3'
>services:
>  netdisco-postgresql:
>    image: netdisco/netdisco:latest-postgresql
>    volumes:
>      - "./netdisco/pgdata:/var/lib/postgresql/data"
>      - /etc/localtime:/etc/localtime:ro
>\#    build:
>\#      context: netdisco-postgresql
>\#  netdisco-base:
>\#    image: netdisco/netdisco:latest-base
>\#    build:
>\#      context: netdisco-base
>\#    scale: 0
>  netdisco-backend:
>    image: netdisco/netdisco:latest-backend
>    restart: unless-stopped
>    volumes:
>      - "./netdisco/nd-site-local:/home/netdisco/nd-site-local"
>      - "./netdisco/config:/home/netdisco/environments"
>      - "./netdisco/logs:/home/netdisco/logs"
>      - /etc/localtime:/etc/localtime:ro
>    environment:
>      NETDISCO_DOMAIN:  discover
>      NETDISCO_DB_HOST: netdisco-postgresql
>    depends_on:
>      - netdisco-postgresql
>    dns_opt:
>      - 'ndots:1'
>      - 'timeout:1'
>      - 'retries:0'
>      - 'attempts:1'
>\#    build:
>\#      context: netdisco-backend
>  netdisco-web:
>    image: netdisco/netdisco:latest-web
>    restart: unless-stopped
>    volumes:
>      - "./netdisco/nd-site-local:/home/netdisco/nd-site-local"
>      - "./netdisco/config:/home/netdisco/environments"
>      - /etc/localtime:/etc/localtime:ro
>\# logs are symlinked to stdout
>\#      - "./netdisco/logs:/home/netdisco/logs"
>    environment:
>      NETDISCO_DOMAIN:  discover
>      NETDISCO_DB_HOST: netdisco-postgresql
>    ports:
>      - "5000:5000"
>    restart: unless-stopped
>   depends_on:
>     - netdisco-postgresql
>    dns_opt:
>     - 'ndots:1'
>      - 'timeout:1'
>     - 'retries:0'
>      - 'attempts:1'
>
> \#    build:
> \#      context: netdisco-web

**Comment by ollyg** [comment]
Yes, it looks (from the logs) like the web frontend cannot make a connection to the database.

In the docker compose file I wonder if the port 5432 needs to be exposed (same as 5000 for web). 

Unfortunately I don't have a docker setup here where I am, so I cannot test. Perhaps another contributor will comment!

**Comment by rc9000** [comment]
Ok I understand now, we broke the docker internal DNS in 0d547e0. Docker relies on `ndots:0` so a name like "netdisco-postgresql" will be looked up first without the search domain appended. E.g. the resolv.conf in the postgresql container where we didn't add options looks like this:

    # cat /etc/resolv.conf 
    search eu-central-1.compute.internal
    nameserver 127.0.0.11
    options edns0 trust-ad ndots:0

@ollyg I'm not quite familiar with the original intention behind these new dns_opts, you think what you wanted to do will still work with the #43 PR? I also added back the edns0 and trust-ad options which docker seems to add automatically, not quite sure if we need them.

**Comment by ollyg** [comment]
Hi @ntaken please download new docker containers (2.049011 on docker hub) and let us know if this fixes it. Thanks!

**Comment by ntaken** [comment]
Yes, it works now! Thanks for all of yours hard work.

> sudo docker-compose up
Starting netdisco_netdisco-postgresql_1 ... done
Starting netdisco_netdisco-backend_1    ... done
Starting netdisco_netdisco-web_1        ... done
Attaching to netdisco_netdisco-postgresql_1, netdisco_netdisco-web_1, netdisco_netdisco-backend_1
netdisco-postgresql_1  | The files belonging to this database system will be owned by user "postgres".
netdisco-postgresql_1  | This user must also own the server process.
netdisco-postgresql_1  |
netdisco-postgresql_1  | The database cluster will be initialized with locale "en_US.utf8".
netdisco-postgresql_1  | The default database encoding has accordingly been set to "UTF8".
netdisco-postgresql_1  | The default text search configuration will be set to "english".
netdisco-postgresql_1  |
netdisco-postgresql_1  | Data page checksums are disabled.
netdisco-postgresql_1  |
netdisco-postgresql_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
netdisco-postgresql_1  | creating subdirectories ... ok
netdisco-postgresql_1  | selecting dynamic shared memory implementation ... posix
netdisco-postgresql_1  | selecting default max_connections ... 100
netdisco-postgresql_1  | selecting default shared_buffers ... 128MB
netdisco-postgresql_1  | selecting default time zone ... Europe/Stockholm
netdisco-postgresql_1  | creating configuration files ... ok
netdisco-postgresql_1  | running bootstrap script ... ok
netdisco-postgresql_1  | performing post-bootstrap initialization ... sh: locale: not found
netdisco-postgresql_1  | 2021-10-12 11:58:53.019 CEST [36] WARNING:  no usable system locales were found
netdisco-postgresql_1  | ok
netdisco-web_1         | config watcher: watching /home/netdisco/environments for updates.
netdisco-backend_1     | config watcher: watching /home/netdisco/environments for updates.
netdisco-web_1         | 2021/10/12-11:58:54 Starman::Server (type Net::Server::PreFork) starting! pid(8)
netdisco-web_1         | Resolved [*]:5000 to [::]:5000, IPv6
netdisco-web_1         | Not including resolved host [0.0.0.0] IPv4 because it will be handled by [::] IPv6
netdisco-web_1         | Binding to TCP port 5000 on host :: with IPv6
netdisco-web_1         | Setting gid to "901 901"
netdisco-postgresql_1  | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
netdisco-postgresql_1  | You can change this by editing pg_hba.conf or using the option -A, or
netdisco-postgresql_1  | --auth-local and --auth-host, the next time you run initdb.
netdisco-postgresql_1  | ok
netdisco-postgresql_1  |
netdisco-postgresql_1  |
netdisco-postgresql_1  | Success. You can now start the database server using:
netdisco-postgresql_1  |
netdisco-postgresql_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
netdisco-postgresql_1  |
netdisco-postgresql_1  | waiting for server to start....2021-10-12 11:58:54.368 CEST [41] LOG:  starting PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
netdisco-postgresql_1  | 2021-10-12 11:58:54.372 CEST [41] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
netdisco-postgresql_1  | 2021-10-12 11:58:54.386 CEST [42] LOG:  database system was shut down at 2021-10-12 11:58:53 CEST
netdisco-postgresql_1  | 2021-10-12 11:58:54.402 CEST [41] LOG:  database system is ready to accept connections
netdisco-postgresql_1  |  done
netdisco-postgresql_1  | server started
netdisco-postgresql_1  | netdisco-db-entrypoint: configuring Netdisco user and db
netdisco-postgresql_1  |
netdisco-postgresql_1  | /usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/netdisco-initdb.sh
netdisco-postgresql_1  | CREATE ROLE
netdisco-web_1         | [9] 2021-10-12 09:58:54  warn App::Netdisco 2.049011 web
netdisco-postgresql_1  | netdisco-db-entrypoint: restarting pg privately to container
netdisco-postgresql_1  | 2021-10-12 11:58:54.944 CEST [41] LOG:  received fast shutdown request
netdisco-postgresql_1  | waiting for server to shut down....2021-10-12 11:58:54.947 CEST [41] LOG:  aborting any active transactions
netdisco-postgresql_1  | 2021-10-12 11:58:54.951 CEST [41] LOG:  background worker "logical replication launcher" (PID 48) exited with exit code 1
netdisco-postgresql_1  | 2021-10-12 11:58:54.952 CEST [43] LOG:  shutting down
netdisco-postgresql_1  | 2021-10-12 11:58:54.982 CEST [41] LOG:  database system is shut down
netdisco-postgresql_1  |  done
netdisco-postgresql_1  | server stopped
netdisco-web_1         | [12] 2021-10-12 09:58:55  warn App::Netdisco 2.049011 web
netdisco-web_1         | [10] 2021-10-12 09:58:55  warn App::Netdisco 2.049011 web
netdisco-postgresql_1  | waiting for server to start....2021-10-12 11:58:55.123 CEST [59] LOG:  starting PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
netdisco-postgresql_1  | 2021-10-12 11:58:55.123 CEST [59] LOG:  listening on IPv4 address "127.0.0.1", port 5432
netdisco-postgresql_1  | 2021-10-12 11:58:55.123 CEST [59] LOG:  could not bind IPv6 address "::1": Address not available
netdisco-postgresql_1  | 2021-10-12 11:58:55.123 CEST [59] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
netdisco-postgresql_1  | 2021-10-12 11:58:55.129 CEST [59] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
netdisco-postgresql_1  | 2021-10-12 11:58:55.139 CEST [60] LOG:  database system was shut down at 2021-10-12 11:58:54 CEST
netdisco-postgresql_1  | 2021-10-12 11:58:55.148 CEST [59] LOG:  database system is ready to accept connections
netdisco-postgresql_1  |  done
netdisco-postgresql_1  | server started
netdisco-postgresql_1  | netdisco-db-entrypoint: bringing schema up-to-date
netdisco-web_1         | [13] 2021-10-12 09:58:55  warn App::Netdisco 2.049011 web
netdisco-web_1         | [11] 2021-10-12 09:58:55  warn App::Netdisco 2.049011 web
netdisco-web_1         | DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
netdisco-web_1         | DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
netdisco-web_1         | Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: The setting session_cookie_key must be defined at /home/netdisco/perl5/lib/perl5/Dancer/Session/Cookie.pm line 38.
netdisco-web_1         | Compilation failed in require at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
netdisco-web_1         | BEGIN failed--compilation aborted at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
netdisco-web_1         | DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
netdisco-web_1         | Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: The setting session_cookie_key must be defined at /home/netdisco/perl5/lib/perl5/Dancer/Session/Cookie.pm line 38.
netdisco-web_1         | Compilation failed in require at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
netdisco-web_1         | BEGIN failed--compilation aborted at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
netdisco-web_1         | Child process 9 exited with status 115
netdisco-web_1         | Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: The setting session_cookie_key must be defined at /home/netdisco/perl5/lib/perl5/Dancer/Session/Cookie.pm line 38.
netdisco-web_1         | Compilation failed in require at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
netdisco-web_1         | BEGIN failed--compilation aborted at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
netdisco-web_1         | Child process 11 exited with status 115
netdisco-web_1         | Child process 12 exited with status 115
netdisco-web_1         | DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
netdisco-web_1         | Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: The setting session_cookie_key must be defined at /home/netdisco/perl5/lib/perl5/Dancer/Session/Cookie.pm line 38.
netdisco-web_1         | Compilation failed in require at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
netdisco-web_1         | BEGIN failed--compilation aborted at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
netdisco-web_1         | Child process 13 exited with status 115
netdisco-web_1         | DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
netdisco-web_1         | Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: The setting session_cookie_key must be defined at /home/netdisco/perl5/lib/perl5/Dancer/Session/Cookie.pm line 38.
netdisco-web_1         | Compilation failed in require at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
netdisco-web_1         | BEGIN failed--compilation aborted at /home/netdisco/perl5/bin/netdisco-web-fg line 59.
netdisco-web_1         | Child process 10 exited with status 115
netdisco-web_1         | [19] 2021-10-12 09:58:56  warn App::Netdisco 2.049011 web
netdisco-web_1         | [20] 2021-10-12 09:58:56  warn App::Netdisco 2.049011 web
netdisco-web_1         | [21] 2021-10-12 09:58:56  warn App::Netdisco 2.049011 web
netdisco-web_1         | [22] 2021-10-12 09:58:56  warn App::Netdisco 2.049011 web
netdisco-postgresql_1  | netdisco-db-entrypoint: importing OUI
netdisco-web_1         | [23] 2021-10-12 09:58:56  warn App::Netdisco 2.049011 web
netdisco-postgresql_1  | COPY 23285
netdisco-postgresql_1  | netdisco-db-entrypoint: marking schema as up-to-date
netdisco-postgresql_1  | netdisco-db-entrypoint: adding admin user if none exists
netdisco-postgresql_1  | INSERT 0 1
netdisco-postgresql_1  | netdisco-db-entrypoint: adding session key if none exists
netdisco-postgresql_1  | INSERT 0 1
netdisco-postgresql_1  | netdisco-db-entrypoint: queueing stats job
netdisco-postgresql_1  | INSERT 0 1
netdisco-postgresql_1  |
netdisco-postgresql_1  | waiting for server to shut down...2021-10-12 11:58:57.035 CEST [59] LOG:  received fast shutdown request
netdisco-postgresql_1  | .2021-10-12 11:58:57.037 CEST [59] LOG:  aborting any active transactions
netdisco-postgresql_1  | 2021-10-12 11:58:57.038 CEST [59] LOG:  background worker "logical replication launcher" (PID 66) exited with exit code 1
netdisco-postgresql_1  | 2021-10-12 11:58:57.047 CEST [61] LOG:  shutting down
netdisco-postgresql_1  | 2021-10-12 11:58:57.143 CEST [59] LOG:  database system is shut down
netdisco-postgresql_1  |  done
netdisco-postgresql_1  | server stopped
netdisco-postgresql_1  |
netdisco-postgresql_1  | PostgreSQL init process complete; ready for start up.
netdisco-postgresql_1  |
netdisco-postgresql_1  | 2021-10-12 11:58:57.258 CEST [1] LOG:  starting PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
netdisco-postgresql_1  | 2021-10-12 11:58:57.259 CEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
netdisco-postgresql_1  | 2021-10-12 11:58:57.259 CEST [1] LOG:  listening on IPv6 address "::", port 5432
netdisco-postgresql_1  | 2021-10-12 11:58:57.265 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
netdisco-postgresql_1  | 2021-10-12 11:58:57.272 CEST [290] LOG:  database system was shut down at 2021-10-12 11:58:57 CEST
netdisco-postgresql_1  | 2021-10-12 11:58:57.277 CEST [1] LOG:  database system is ready to accept connections
