### ISSUE TITLE
After installing latest NetDisco from docker Hub NetDisco refuses to find anything 

### ISSUE THREAD

**Issue by StewAlexander-com** [netdisco/netdisco-docker#48]
@ollyg:

After installing the latest NetDisco from Docker hub, NetDisco refuses to find anything under the Discover all

![image](https://user-images.githubusercontent.com/48565067/179237549-029f9e67-1a21-4f35-81a2-cee5391296cd.png)

I can ping the Cisco switch from the Docker server (the thing holding the containers):

![image](https://user-images.githubusercontent.com/48565067/179238206-949054be-1964-452f-86d1-1c16e1d06712.png)

But all there are are failed SNMP connections:

![image](https://user-images.githubusercontent.com/48565067/179238413-402a076d-eaa8-43e0-b26b-8496d5c076d3.png)

The host system is Ubuntu ```DISTRIB_RELEASE=18.04```

I think I found the problem:
![image](https://user-images.githubusercontent.com/48565067/179239274-cbce7160-118b-4de5-85e4-b4aed930e696.png)

I'll try configuring this with our community string and see if this helps

Yup, fixed - you might want to add this to the notes on docker hub that you'll need to change the community string under the deployment file

**Comment by rc9000** [comment]
Hi @StewAlexander-com , I tried to reproduce this like so

 * create the directories like shown in the README.md
 * create docker-compose.yml: `curl -Ls -o docker-compose.yml https://tinyurl.com/nd2-dockercompose`
 * sed -e 's/latest/2.052007/g' to start with an older version so we have something to upgrade
 * `docker-compose up`, then I applied some changes in the communities
 * `docker-compose down`, `sed -e 's/2.052007/latest/g'`, `docker-compose pull`, `docker-compose up`
 * It looks like this leaves deployment.yml untouched, and my changes are still there.

Was this roughly how you did the upgrade? And it looks like your whole deployment.yml was replaced by the default version?

**Comment by StewAlexander-com** [comment]
@rc9000 

I tried to just do a docker recreate from portainer, and that messed up everything, it would just hang (my version of NetDisco was three years old, so unsure if that had anything to do with it) - so I deleted the ~/netdisco folder and everything it contained ...

So, yeah it created a new deployment file as it was more or less a fresh install -- still I didn't see in there that I needed to update the SNMP community string in the deployment file -- even on a new install (maybe I overlooked this?)

Thanks for the additional info though in there - hopefully on the next upgrade it would save some headache since I'll use the nice docker compose file you all spent time building .... 

Thank you to you and team for the hard work on this, really helpful where I work, [Alamance Community College](https://Alamancecc.edu)
