### ISSUE TITLE
netdisco_default network address change

### ISSUE THREAD

**Issue by cweakland** [netdisco/netdisco-docker#57]
## Expected Behavior
I am unable to find and change the definition for the network/mask that the netdisco_default bridge uses.

## Current Behavior
The netdisco_default bridge network is 172.20.0.1/16, this network is used in my traditional networking environment. I would like to change this to avoid the addressing conflict. 

## Possible Solution
Could this be added in the docker compose file so that it can be changed?

## Your Environment

* netdisco container versions: 
  * netdisco-postgresql: 13.0.0.4
  * netdisco-backend: 2.60.10 ?
  * netdisco-web: 2.60.10 ?
* docker engine version: docker-ce 5:23.0.2-1~ubuntu.22.04~jammy
* docker-compose version: docker-compose  1.29.2-1 
* host operating system: Ubuntu 22.04

**Comment by rc9000** [comment]
Sorry nobody got around to look at this for multiple months. The easiest way is to change the default pools in daemon.json, then do a docker-compose down/up to recreate everything.

https://medium.com/@jacob.swanson.n/making-docker-use-different-ip-ranges-on-ubuntu-27ba6cbb825d
