### ISSUE TITLE
Add debug modules to build

### ISSUE THREAD

**Issue by jnovak-netsystemcz** [netdisco/netdisco-docker#58]
I need to troubleshoot netdisco in docker and I followed App::Netdisco::Manual::Troubleshooting. The issue is that required modules are not in images.

Is it possible to add it to default images or publish derived images with debug modules?

**Comment by rc9000** [comment]
You can install the module in a running container like so:

    # root shell in running container
    docker-compose exec -u root   netdisco-web sh

    # in Ubuntu, I had to vi /etc/resolv.conf here and add 8.8.8.8 since otherwise
    # i was not able to resolve external DNS names 
    #  /home/netdisco # cat /etc/resolv.conf
    #  #nameserver 127.0.0.11
    #  nameserver 8.8.8.8
    # ...

    # then:
    apk add  g++ make
    ~netdisco/bin/localenv cpanm --notest --verbose Dancer::Debug

This modified image will then be used until the next `docker-compose down`, ie. it survives start/stop if you need to restart. 

But I would also be open to just add Dancer::Debug to https://github.com/netdisco/netdisco/blob/master/Build.PL so it's always available for everybody.

**Comment by rc9000** [comment]
Closing this for now, @jnovak-netsystemcz let us know if installing manually in the container didn't work out and you strongly prefer it should be included by default.
