### ISSUE TITLE
Inventory not populated, unless you search explicitly from the web interface

### ISSUE THREAD

**Issue by bbird81** [netdisco/netdisco-docker#67]
Hi! I'm trying to use netdisco in its docker form to extract some infos from my network devices. Since I'm trying to use it in a fully automated environment, I don't want to use the web interface at all: I just generate the deployment.yml file, fire the containers and then I directly extract what I need from the DB.

Everything works just fine, beside a very important detail: even though I populated correctly the inventory through deployment.yml, nothing is **ever** discovered, unless I first try to discover at least one device through the web interface. If I try that, then magically all the devices in the deployment.yml are discovered as well.

Thanks for any help/insight!

## Expected Behavior

When firing the containers, devices should be discovered according to schedule defined in deployment.yml.

## Current Behavior
Discovery is never started, Inventory is empty (clicking the page brings you back to the homepage) unless interaction from the web interface happens, trying to discover at least one ip using this field:
![image](https://github.com/netdisco/netdisco-docker/assets/25413624/365e7ac0-e92e-44a9-81b6-d93d857e0b00)

## Possible Solution
Implement a way to "wake up" the thing (even though I assume that it should have done it by itself, which would be best), maybe using netdisco-do; but it must NOT rely on knowing a specific ip to discover (e.g. run a generic operation like netdisco-do stats). This currently doesn't work but would be enough to solve the problem.

## Steps to Reproduce (for bugs)

1. Make default installation of netdisco-docker
2. Provide a deployment.yml in the correct directory (below mine).
3. Verify that the Inventory and the DB are never populated.

## Context

I'm trying to use it in a fully automated environment, I don't want to use the web interface at all: I just generate the deployment.yml file and then I directly extract what I need from the DB using another container I built.

## Your Environment

* netdisco container versions: 2.74.1 and 2.72.1 (tried these two, neither works)
* docker engine version: 24.0.7
* docker-compose version: v2.21.0
* host operating system: 5.15.0-86-generic #96-Ubuntu.

## Config info (deployment.yml and docker env settings)
`
site_local_files: true
no_auth: true

host_groups:
  discover_only:
    - 192.168.83.10-13
    - 192.168.83.6

devices_only:
  - 'group:discover_only'

device_auth:
  - tag: 'default_v2'
    community: xxx
    read: true
    write: false

schedule:
  discoverall:
    when: '55 09,14 * * *'
  macwalk:
    when: '55 09,14 * * *'
  arpwalk:
    when: '55 09,14 * * *'
  nbtwalk: null
  expire:
    when: '30 23 * * *'
  makerancidconf: null
`

## Device information
All devices are Cisco, various platforms, it doesn't seem to be related to which device is defined in the inventory.

**Comment by rc9000** [comment]
A recent release just added a ["pingsweep" to netdisco-do](https://metacpan.org/pod/netdisco-do#pingsweep). Could you just run `netdisco-do pingsweep --enqueue 192.168.83.0/24` somewhere in your process, then together with your discover_only setup it should combine to discovery everything replies in your ranges. 

If you want to write it more generically use a larger range in the pingsweep that matches your networks. 

For netdisco to start polling without a single seed device as you describe is difficult to support in a generic way, since one can have a deployment.yml without a single ip or network in it to get started on.

**Comment by bbird81** [comment]
> A recent release just added a ["pingsweep" to netdisco-do](https://metacpan.org/pod/netdisco-do#pingsweep). Could you just run `netdisco-do pingsweep --enqueue 192.168.83.0/24` somewhere in your process, then together with your discover_only setup it should combine to discover everything replies in your ranges.
> 
> If you want to write it more generically use a larger range in the pingsweep that matches your expected networks.

Hi, thanks for the idea :) unfortunately it doesn't really resolve my problem as I would have to know the target of the pingsweep... Devices might not be all in the same subnet for instance, like 10.0.0.1 and 192.168.0.1: if I ping one, would it discover the other one as well? Anyway it's a nice idea and worth a shot.

> For netdisco to start polling without a single seed device as you describe is difficult to support in a generic way, since one can have a deployment.yml without a single ip or network in it to get started on.

So this is by design? There's no "internal" trigger (e.g. like running something in the backend container...?) that forces the backend to discover what I configured in the deployment.yaml?

**Comment by rc9000** [comment]
Theoretically Netdisco can discover your whole network from one well-connected seed device, it uses various neighbor discovery protocols. But it's easy to break this by a single hop that has LLDP disabled, so typically you'll want more than one, e.g. one router per building in all your branch locations. 

How do you get the ranges you put into discover_only right now? Maybe you can just ping sweep all of these?

**Comment by bbird81** [comment]
The IPs are inserted manually into a scripts that generates the whole configuration (docker-compose.yml, deployment.yml etc) so I might add at the end, after composing, a pingsweep command, that's definitely something I could do.

To understand better, I tried to make a pingsweep on a single ip just to make a test (I've used 192.168.83.6) and that + two other devices (192.168.83.10 & .12) became available in the inventory... I don't understand, I find it a little bit weird/random: shouldn't that just make the .6 available? How can I be sure, on the other hand, that if I ping sweep the entire network, no devices will be missed from my list? And what happens if in the range that I sweep (let's say a /24) I have other devices that I DON'T want to incorporate in that moment? Will Netdisco try to discover them?

Sorry, I don't want to be annoying, I'm just trying to understand what's the logic behind this.

Thank you for your answers, I greatly appreciate them.

**Comment by rc9000** [comment]
Don't worry these are all valid questions :)

> other devices (192.168.83.10 & .12) became available in the inventory.

This is the neighbor discovery mechanism, when discovering one device Netdisco looks at the neighbors via CDP/LLDP/BGP/etc, and tries to discover the neighbors too. You can disable or limit this "infectious" discovery via discover_neighbors/discover_routed_neighbors/skip_neighbors configuration.

> How can I be sure, on the other hand, that if I ping sweep the entire network, no devices will be missed from my list? 

You really can't, as a lot of stuff can go wrong with discovering a device: your config doesn't have a valid SNMP community for it, device has ACLs, unreachable etc.... to be really sure you'd need to know the exact list that should be there, compare with what was found, and go investigate what went wrong with each device that's missing.

> And what happens if in the range that I sweep (let's say a /24) I have other devices that I DON'T want to incorporate

You'd add them into the `discover_no` configuration.

**Comment by bbird81** [comment]
Great explanations, thank you! Now it's clear. You are very kind and patient :)

May I ask you one more question please? I noticed that in the containers date is set to UTC, therefore the schedule put in deployment.yml uses UTC as timezone, even though the host machine is in another TZ.

Is there any way to change/configure that? I'm asking this because I'm in CEST and the schedule run 2h after what I put in the deployment.yml.
I could just anticipate by 2h but this would not follow the summer/winter pattern... I could install tzdata via `docker run apk add` but I wanted to put everything in an air-gapped environment, so it would be better to have a solution that doesn't rely on Internet connection.

Is there anything you could suggest to resolve this scenario? Maybe I'm missing some configuration somewhere? Thank you :)

**Comment by rc9000** [comment]
tzdata should already be installed in the current container image. You can set TZ in the docker environment and timezone in postgresql.conf, see e.g. https://github.com/netdisco/netdisco-docker/issues/46 

This only works well if all your users + devices are in the same time zone and is not extensively tested or supported, but it seems to do ok for the people that tried so far.

**Comment by rc9000** [comment]
oh you're right, we've added tzdata once but it was in the wrong place. The next release should include it in all the images.

**Comment by bbird81** [comment]
Thank you very much. Closing the issue as everything seems to be sorted out.
THANK YOU 👍
