### ISSUE TITLE
cluster docker 

### ISSUE THREAD

**Issue by mrfrtr** [netdisco/netdisco-docker#74]
hi use docker deployment can ı do stack for more worker ı want deploy more then 1 backend becasue my network so big

**Comment by ollyg** [comment]
Hi @mrfrtr 
You can increase the CPU resources of the backend and increase the number of workers in configuration.
If you want to run multiple backend containers, yes that is possible. Each backend must have a unique hostname and connect to the same database, then they will all share jobs.
I hope this helps,
