### ISSUE TITLE
Make “complete” image

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco-docker#9]
Will need to baseit off the pg image
Will need to add init system to run two daemons
Have Netdisco-do as entrypoint?

**Comment by djzort** [comment]
merging pg image makes it harder to upgrade?

**Comment by ollyg** [comment]
I think it should be okay - what were you thinking of as the problem?
(note that the pg datafiles are stored in a VOLUME so persist outside of the container)

However I would suggest users only use the complete image to trial Netdisco and use separate images if they choose to run longterm.

**Comment by LBegnaud** [comment]
I just want to say @ollyg you've made this image so much better than I imagined possible.

Looking forward to testing it out!
